// mysterious/src/lib/components/Modal.svelte
<script lang="ts">
    export let modal_id:string 
    export let modal_title: string
    export let action_button_class: string = "btn btn-primary"
</script>
<input type="checkbox" id="{modal_id}" class="modal-toggle" />
<div class="modal modal-bottom sm:modal-middle">
    <div class="modal-box relative">
        
    <label for="{modal_id}" class="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
    <h3 class="font-bold text-lg mb-4">{modal_title}</h3>
    <slot name="body"></slot>
    <div class="modal-action">
        <label on:click for="{modal_id}" class="{action_button_class}">Submit</label>
    </div>
    </div>
</div>

// kiyotaka/modal/Modal.tsx
import React from "react";
import { GlobalContext } from "../context/ContextApi";

const Modal = () => {
  const { Create, ReadData, loading, status, data, setData } =
    React.useContext(GlobalContext);
  const handlerSubmit = () => {
    if (status === "create" || status === "update") {
      return Create({ ...data });
    }
    return ReadData({ id: data.id });
  };

  const style = {
    form: "flex flex-col gap-[12px] w-full gap-[24px]",
    input: "input input-bordered p-[12px]",
    textarea: "input input-bordered h-[200px] p-[12px] resize-none w-full ",
  };

  const handlerStatus = () => {
    if (status === "create" || status === "update") {
      return true;
    }
    return false;
  };

  return (
    <div>
      <input type="checkbox" id="my-modal" className="modal-toggle" />
      <div className="modal">
        <div className="modal-box flex flex-col gap-[24px] items-start relative">
          <label
            htmlFor="my-modal"
            className="btn btn-sm btn-circle absolute right-2 top-2"
          >
            ✕
          </label>
          <h2 className="font-bold text-xl font-sans">
            {status} data to inery
          </h2>
          <form className={style.form}>
            <input
              className={style.input}
              placeholder="type any number"
              value={data.id}
              onChange={(e) => setData({ ...data, id: e.target.value })}
            />
            {handlerStatus() && (
              <input
                value={data.user}
                disabled={true}
                className={style.input}
              />
            )}
            {handlerStatus() && (
              <textarea
                className={style.textarea}
                placeholder="type any data"
              />
            )}
          </form>
          <label htmlFor={"my-modal"} className="btn" onClick={handlerSubmit}>
            {loading ? "loading..." : status}
          </label>
        </div>
      </div>
    </div>
  );
};

export default Modal;
